name: bus_arrivals_application_image

on:
  push:
    branches: ['main']
  pull_request:
    branches: none

  # Allow running the workflow from the Actions Tab
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: konsitistas/bus_arrivals_application

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout # Give access to the workflow
      uses: actions/checkout@v2
    -
      name: Create .env file
      run: echo ${{secrets.API_KEY}} > .env
    -
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/bus_arrivals_application:latest
        # Using build cache to reduce build time and reduce number of pulls in Docker Hub
        cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/bus_arrivals_application:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/bus_arrivals_application:buildcache,mode=max
