name: bus_arrivals_application_image

on:
  push:
    branches: ['main']
  pull_request:
    branches: none

  # Allow running the workflow from the Actions Tab
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout # Give access to the workflow
      uses: actions/checkout@v2
    -
      name: Create .env file
      run: echo ${{secrets.API_KEY}} > .env
    -
      name: Login to Docker Hub
#       uses: docker/login-action@v1
#       with:
#         username: ${{ secrets.DOCKER_HUB_USERNAME }}
#         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      run: | 
        echo $CR_PAT | docker login ghcr.io -u sitistas --password-stdin
      env:
        CR_PAT: ${{ secrets.CR_PAT }}
#     -
#       name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v1
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ secrets.DOCKER_HUB_USERNAME }}/bus_arrivals_application:latest
        # Using build cache to reduce build time and reduce number of pulls in Docker Hub
        cache-from: type=registry,ref=ghcr.io/${{ secrets.DOCKER_HUB_USERNAME }}/bus_arrivals_application:buildcache
        cache-to: type=registry,ref=ghcr.io/${{ secrets.DOCKER_HUB_USERNAME }}/bus_arrivals_application:buildcache,mode=max
